In [ ]:
# Route Efficiency Score


import pandas as pd

# Load the final route analysis from Step 6
final_route_analysis = pd.read_csv(
    r"D:\Nassu Project\Nassau-Candy-Shipping-Analysis\data\processed\route_efficiency_analysis.csv",
    index_col=0
)

# Calculate minimum and maximum average lead time
min_lead_time = final_route_analysis["Average_Lead_Time"].min()
max_lead_time = final_route_analysis["Average_Lead_Time"].max()

# Calculate Route Efficiency Score
final_route_analysis["Efficiency_Score"] = (
    100 * (
        1 -
        (
            final_route_analysis["Average_Lead_Time"] - min_lead_time
        ) /
        (
            max_lead_time - min_lead_time
        )
    )
)

# Round the score for easier reading
final_route_analysis["Efficiency_Score"] = (
    final_route_analysis["Efficiency_Score"].round(2)
)

# Sort from most efficient to least efficient
final_route_analysis = final_route_analysis.sort_values(
    "Efficiency_Score",
    ascending=False
)

print("Route Efficiency Score:")
display(final_route_analysis.head(20))

Route Efficiency Score:

,Shipment_Volume,Average_Lead_Time,Minimum_Lead_Time,Maximum_Lead_Time,Delayed_Shipments,Delay_Frequency,Efficiency_Score
Route,,,,,,,
Wicked Choccy's → Nevada,12,1182.250000,908,1639,1,8.333333,100.00
Secret Factory → Texas,16,1227.062500,905,1641,3,18.750000,85.39
Lot's O' Nuts → Virginia,109,1229.486239,905,1641,15,13.761468,84.60
Wicked Choccy's → South Carolina,19,1234.210526,904,1641,2,10.526316,83.05
Lot's O' Nuts → Utah,29,1236.000000,906,1640,6,20.689655,82.47
Wicked Choccy's → Virginia,106,1238.877358,904,1642,13,12.264151,81.53
Wicked Choccy's → Mississippi,22,1240.454545,907,1640,2,9.090909,81.02
Lot's O' Nuts → Nevada,24,1243.250000,904,1641,4,16.666667,80.11
Wicked Choccy's → Quebec,24,1243.583333,907,1642,7,29.166667,80.00
Lot's O' Nuts → Oregon,77,1245.194805,906,1642,13,16.883117,79.47
Lot's O' Nuts → Ontario,28,1246.285714,906,1639,1,3.571429,79.12
Wicked Choccy's → Ontario,30,1248.566667,906,1639,4,13.333333,78.37
Lot's O' Nuts → Kansas,15,1248.866667,908,1639,1,6.666667,78.27
Wicked Choccy's → Louisiana,15,1272.266667,906,1640,2,13.333333,70.64
Lot's O' Nuts → New Hampshire,13,1272.461538,906,1637,0,0.000000,70.58
Wicked Choccy's → Alabama,22,1272.727273,906,1639,5,22.727273,70.49
Wicked Choccy's → Connecticut,31,1272.870968,904,1642,6,19.354839,70.45
Lot's O' Nuts → Delaware,43,1273.302326,906,1641,9,20.930233,70.31
Wicked Choccy's → Utah,23,1273.478261,909,1639,4,17.391304,70.25
Wicked Choccy's → Arkansas,27,1273.518519,908,1642,6,22.222222,70.24

In [ ]:
# Top 10 and Bottom 10 Routes

# Top 10 most efficient routes
top_10_routes = (
    final_route_analysis
    .sort_values("Efficiency_Score", ascending=False)
    .head(10)
)

print("Top 10 Most Efficient Routes: ")
display(top_10_routes[
    [
        "Shipment_Volume",
        "Average_Lead_Time",
        "Delayed_Shipments",
        "Delay_Frequency",
        "Efficiency_Score"
    ]
])

# Bottom 10 least efficient routes
bottom_10_routes = (
    final_route_analysis
    .sort_values("Efficiency_Score", ascending=True)
    .head(10)
)

print("Bottom 10 Least Efficient Routes:")
display(bottom_10_routes[
    [
        "Shipment_Volume",
        "Average_Lead_Time",
        "Delayed_Shipments",
        "Delay_Frequency",
        "Efficiency_Score"
    ]
])

Top 10 Most Efficient Routes:

,Shipment_Volume,Average_Lead_Time,Delayed_Shipments,Delay_Frequency,Efficiency_Score
Route,,,,,
Wicked Choccy's → Nevada,12,1182.250000,1,8.333333,100.00
Secret Factory → Texas,16,1227.062500,3,18.750000,85.39
Lot's O' Nuts → Virginia,109,1229.486239,15,13.761468,84.60
Wicked Choccy's → South Carolina,19,1234.210526,2,10.526316,83.05
Lot's O' Nuts → Utah,29,1236.000000,6,20.689655,82.47
Wicked Choccy's → Virginia,106,1238.877358,13,12.264151,81.53
Wicked Choccy's → Mississippi,22,1240.454545,2,9.090909,81.02
Lot's O' Nuts → Nevada,24,1243.250000,4,16.666667,80.11
Wicked Choccy's → Quebec,24,1243.583333,7,29.166667,80.00
Lot's O' Nuts → Oregon,77,1245.194805,13,16.883117,79.47

Bottom 10 Least Efficient Routes:

,Shipment_Volume,Average_Lead_Time,Delayed_Shipments,Delay_Frequency,Efficiency_Score
Route,,,,,
Wicked Choccy's → New Mexico,17,1488.882353,11,64.705882,0.00
Lot's O' Nuts → Iowa,16,1479.000000,6,37.500000,3.22
Secret Factory → Washington,11,1472.363636,2,18.181818,5.39
Lot's O' Nuts → New Mexico,18,1456.944444,10,55.555556,10.42
Wicked Choccy's → Manitoba,10,1455.600000,4,40.000000,10.85
Lot's O' Nuts → Connecticut,47,1420.553191,17,36.170213,22.28
Wicked Choccy's → Iowa,14,1403.785714,4,28.571429,27.75
Wicked Choccy's → Indiana,54,1402.462963,23,42.592593,28.18
Wicked Choccy's → Tennessee,67,1393.761194,22,32.835821,31.02
Lot's O' Nuts → Tennessee,109,1390.963303,34,31.192661,31.93

In [7]:
# Efficiency Score vs Delay Frequency

# Select important columns for comparison
efficiency_delay_comparison = final_route_analysis[
    [
        "Shipment_Volume",
        "Average_Lead_Time",
        "Delay_Frequency",
        "Efficiency_Score"
    ]
].copy()

# Sort by Efficiency Score
efficiency_delay_comparison = (
    efficiency_delay_comparison
    .sort_values("Efficiency_Score", ascending=False)
)

print("Efficiency Score vs Delay Frequency:")
display(efficiency_delay_comparison.head(20))

Efficiency Score vs Delay Frequency:

,Shipment_Volume,Average_Lead_Time,Delay_Frequency,Efficiency_Score
Route,,,,
Wicked Choccy's → Nevada,12,1182.250000,8.333333,100.00
Secret Factory → Texas,16,1227.062500,18.750000,85.39
Lot's O' Nuts → Virginia,109,1229.486239,13.761468,84.60
Wicked Choccy's → South Carolina,19,1234.210526,10.526316,83.05
Lot's O' Nuts → Utah,29,1236.000000,20.689655,82.47
Wicked Choccy's → Virginia,106,1238.877358,12.264151,81.53
Wicked Choccy's → Mississippi,22,1240.454545,9.090909,81.02
Lot's O' Nuts → Nevada,24,1243.250000,16.666667,80.11
Wicked Choccy's → Quebec,24,1243.583333,29.166667,80.00
Lot's O' Nuts → Oregon,77,1245.194805,16.883117,79.47
Lot's O' Nuts → Ontario,28,1246.285714,3.571429,79.12
Wicked Choccy's → Ontario,30,1248.566667,13.333333,78.37
Lot's O' Nuts → Kansas,15,1248.866667,6.666667,78.27
Wicked Choccy's → Louisiana,15,1272.266667,13.333333,70.64
Lot's O' Nuts → New Hampshire,13,1272.461538,0.000000,70.58
Wicked Choccy's → Alabama,22,1272.727273,22.727273,70.49
Wicked Choccy's → Connecticut,31,1272.870968,19.354839,70.45
Lot's O' Nuts → Delaware,43,1273.302326,20.930233,70.31
Wicked Choccy's → Utah,23,1273.478261,17.391304,70.25
Wicked Choccy's → Arkansas,27,1273.518519,22.222222,70.24

In [8]:
# Calculate median benchmarks
efficiency_benchmark = final_route_analysis["Efficiency_Score"].median()
delay_benchmark = final_route_analysis["Delay_Frequency"].median()

print("Efficiency Score Benchmark:", efficiency_benchmark)
print("Delay Frequency Benchmark:", delay_benchmark)


# Create route performance classification
def classify_route(row):

    if (
        row["Efficiency_Score"] >= efficiency_benchmark
        and row["Delay_Frequency"] <= delay_benchmark
    ):
        return "Efficient & Low Delay"

    elif (
        row["Efficiency_Score"] >= efficiency_benchmark
        and row["Delay_Frequency"] > delay_benchmark
    ):
        return "Efficient but Delay-Prone"

    elif (
        row["Efficiency_Score"] < efficiency_benchmark
        and row["Delay_Frequency"] <= delay_benchmark
    ):
        return "Inefficient but Low Delay"

    else:
        return "Inefficient & Delay-Prone"


final_route_analysis["Route_Classification"] = (
    final_route_analysis.apply(
        classify_route,
        axis=1
    )
)


# Display classification results
print("Route Performance Classification:")
display(
    final_route_analysis[
        [
            "Shipment_Volume",
            "Average_Lead_Time",
            "Delay_Frequency",
            "Efficiency_Score",
            "Route_Classification"
        ]
    ].head(20)
)

Efficiency Score Benchmark: 56.205
Delay Frequency Benchmark: 20.45185185185185
Route Performance Classification:

,Shipment_Volume,Average_Lead_Time,Delay_Frequency,Efficiency_Score,Route_Classification
Route,,,,,
Wicked Choccy's → Nevada,12,1182.250000,8.333333,100.00,Efficient & Low Delay
Secret Factory → Texas,16,1227.062500,18.750000,85.39,Efficient & Low Delay
Lot's O' Nuts → Virginia,109,1229.486239,13.761468,84.60,Efficient & Low Delay
Wicked Choccy's → South Carolina,19,1234.210526,10.526316,83.05,Efficient & Low Delay
Lot's O' Nuts → Utah,29,1236.000000,20.689655,82.47,Efficient but Delay-Prone
Wicked Choccy's → Virginia,106,1238.877358,12.264151,81.53,Efficient & Low Delay
Wicked Choccy's → Mississippi,22,1240.454545,9.090909,81.02,Efficient & Low Delay
Lot's O' Nuts → Nevada,24,1243.250000,16.666667,80.11,Efficient & Low Delay
Wicked Choccy's → Quebec,24,1243.583333,29.166667,80.00,Efficient but Delay-Prone
Lot's O' Nuts → Oregon,77,1245.194805,16.883117,79.47,Efficient & Low Delay
Lot's O' Nuts → Ontario,28,1246.285714,3.571429,79.12,Efficient & Low Delay
Wicked Choccy's → Ontario,30,1248.566667,13.333333,78.37,Efficient & Low Delay
Lot's O' Nuts → Kansas,15,1248.866667,6.666667,78.27,Efficient & Low Delay
Wicked Choccy's → Louisiana,15,1272.266667,13.333333,70.64,Efficient & Low Delay
Lot's O' Nuts → New Hampshire,13,1272.461538,0.000000,70.58,Efficient & Low Delay
Wicked Choccy's → Alabama,22,1272.727273,22.727273,70.49,Efficient but Delay-Prone
Wicked Choccy's → Connecticut,31,1272.870968,19.354839,70.45,Efficient & Low Delay
Lot's O' Nuts → Delaware,43,1273.302326,20.930233,70.31,Efficient but Delay-Prone
Wicked Choccy's → Utah,23,1273.478261,17.391304,70.25,Efficient & Low Delay
Wicked Choccy's → Arkansas,27,1273.518519,22.222222,70.24,Efficient but Delay-Prone

In [9]:
# Save the final Step 7 analysis
final_route_analysis.to_csv(
    r"D:\Nassu Project\Nassau-Candy-Shipping-Analysis\data\processed\final_route_efficiency_analysis.csv",
    index=True
)

print("Final Step 7 route efficiency analysis saved successfully.")

Final Step 7 route efficiency analysis saved successfully.